### ISSUE TITLE
(nucleus): Deployment with broken component never finishes

### ISSUE THREAD

**Issue by supergillis** [aws-greengrass/aws-greengrass-nucleus#1161] opened 2022-02-03 09:50 UTC
**Describe the bug**

A deployment with a component that ends up in `BROKEN` state never completes. Deploying a new version of the `BROKEN` component never succeeds.

First deployment fails.

```
merge-config. merge-config-service BROKEN. {serviceName=com.gillis.HelloWorld}
merge-config. Deployment failed. {deploymentId=5cc1ba3a-7fb7-414d-8897-235bdb02c887}
```

Second deployment with a new version of the component never starts because the first deployment cannot be canceled.

```
Received new deployment notification. Requesting details. {ThingName=device-1}
Received Iot job description. {Status=QUEUED, queueAt=Thu Feb 03 09:34:16 UTC 2022, ThingName=device-1, JobId=b18928ed-7c26-433c-b041-2eda58729cd7}
Added the job to the queue. {ThingName=device-1, JobId=b18928ed-7c26-433c-b041-2eda58729cd7}
Canceling current deployment. {DeploymentId=b456bda4-ace8-445d-933f-8f374c69aea5, serviceName=DeploymentService, currentState=RUNNING}
Deployment is in a stage where it cannot be cancelled, need to wait for it to finish. {DeploymentId=b456bda4-ace8-445d-933f-8f374c69aea5, serviceName=DeploymentService, currentState=RUNNING}
```

**To Reproduce**

1. Create a component that exits with an exit code other than `0`.
2. Deploy the component.
3. The component will enter `BROKEN` state.
4. The deployment fails but stays in the deployment queue.
5. Deploy a new version of the component.
6. The deployment is never picked up because the previous deployment cannot be canceled.

**Expected behavior**

The deployment with the `BROKEN` component finishes and the next deployment on the job queue starts.

**Actual behavior**

The deployment with the `BROKEN` component never finishes and the next deployment never starts.

**Environment**
 - OS: Amazon Linux 2 in Docker container
 - JDK version: Both on Corretto 11 and OpenJDK 11
 - Nucleus version: `2.5.3`

**Additional context**

This issue on AWS re:Post looks similar
https://repost.aws/questions/QUIfDHBxjcRbSaHwgqo6NKww/greengrass-v-2-removing-containerized-lambda-corrupts-deployment

**Comment by junfuchen99** [comment] 2022-02-03 19:51
Hello @supergillis,

Could you provide complete `greengrass.log` from the incident reported?

From the information you provided, deployment with `deploymentId=5cc1ba3a-7fb7-414d-8897-235bdb02c887` failed  and deployment with `DeploymentId=b456bda4-ace8-445d-933f-8f374c69aea5` cannot be cancelled. Since the deployment ids do not match, something else probably happened in between which caused the latter deployment incomplete.

Thank you.

**Comment by supergillis** [comment] 2022-02-04 09:38
Hello @junfuchen99,

You can find the complete log here:
[deployment.log](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/8001645/deployment.log). Note, these are other deployment IDs than in the original bug report.

It looks like the `DeploymentConfigMerger` might be the one blocking the deployment.

```
2022-01-31T13:08:52.661Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentConfigMerger: merge-config. Applying deployment changes, deployment cannot be cancelled now. {deployment=e6f05803-7431-475c-bcd5-d8eeb4c67190}
..

```

**Comment by shaguptashaikh** [comment] 2022-02-09 19:32
Hi supergillis, from the log snippet you provided, it looks like when your HelloWorld component broke, the deployment was rolled back and as part of that, it tried to remove the components you were deploying i.e. HelloWorld, Log manager and Shadow manager, it seems to have gotten stuck while removing one of the components. I'll try to reproduce this myself, meanwhile would appreciate if you are able to provide more information to help us debug - 

- Are you consistently seeing this issue?
- Were there any further logs about the deployment or the involved components than the snippet you provided?
- Will you be able to enable DEBUG logs and share those?

**Comment by rightpeter** [comment] 2022-02-18 01:00
Close the issue because of no respond. Feel free to re-open it if the issue still exists and more information can be provided.

**Closed** 2022-02-28 19:01 UTC
Labels: bug
