### ISSUE TITLE
PubSubIPCEventStreamAgent.java: NullPointerException if event stream connect sends empty string for the auth token

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#880] opened 2021-03-03 11:17 UTC
If you are using the IPC layer and send an empty auth token in the connect message:

{ "authToken":""}

and then immediately send an aws.greengrass#SubscribeToTopic message 

{"topic":"test/topic"}

the service will throw a null pointer exception. I think it is probably to do with unsafely dereferencing the auth data here:

            serviceName = context.getAuthenticationData().getIdentityLabel();

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/64fe5564de21d3ef12da92b9160c9af3b0840bde/src/main/java/com/aws/greengrass/builtin/services/pubsub/PubSubIPCEventStreamAgent.java#L216

Here's a dump of the error message:

2021-03-03T10:55:46.375Z [INFO] (Thread-4) software.amazon.awssdk.eventstreamrpc.RpcServer: New connection code [AWS_ERROR_SUCCESS] for [Id 27, Class ServerConnection, Refs 1](2021-03-03T10:55:46.372765Z) - <null>. {}
2021-03-03T10:55:46.440Z [ERROR] (Thread-4) com.aws.greengrass.ipc.IPCEventStreamService: Received empty auth token to authenticate IPC client. {}
2021-03-03T10:55:46.441Z [ERROR] (Thread-4) software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler: class java.lang.RuntimeException occurred while attempting to authN/authZ connect: Received empty auth token to authenticate IPC client. {}
java.lang.RuntimeException: Received empty auth token to authenticate IPC client
        at com.aws.greengrass.ipc.IPCEventStreamService.ipcAuthenticationHandler(IPCEventStreamService.java:215)
        at com.aws.greengrass.ipc.IPCEventStreamService.lambda$startup$2(IPCEventStreamService.java:104)
        at software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler.onConnectRequest(ServiceOperationMappingContinuationHandler.java:85)
        at software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler.onProtocolMessage(ServiceOperationMappingContinuationHandler.java:39)
        at software.amazon.awssdk.crt.eventstream.ServerConnectionHandler.onProtocolMessage(ServerConnectionHandler.java:49)

2021-03-03T10:55:46.446Z [INFO] (Thread-4) software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler: Sending connect response for null. {}
Exception in thread "Thread-4" java.lang.NullPointerException
        at com.aws.greengrass.builtin.services.pubsub.PubSubIPCEventStreamAgent$SubscribeToTopicOperationHandler.<init>(PubSubIPCEventStreamAgent.java:210)
        at com.aws.greengrass.builtin.services.pubsub.PubSubIPCEventStreamAgent.getSubscribeToTopicHandler(PubSubIPCEventStreamAgent.java:62)
        at com.aws.greengrass.ipc.modules.PubSubIPCService.lambda$startup$0(PubSubIPCService.java:50)
        at software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler.onIncomingStream(ServiceOperationMappingContinuationHandler.java:139)
        at software.amazon.awssdk.crt.eventstream.ServerConnectionHandler.onIncomingStream(ServerConnectionHandler.java:63)
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000, pid=6770, tid=6829
#
# JRE version: OpenJDK Runtime Environment (11.0.9.1+1) (build 11.0.9.1+1-post-Raspbian-1deb10u2)
# Java VM: OpenJDK Server VM (11.0.9.1+1-post-Raspbian-1deb10u2, mixed mode, serial gc, linux-)
# Problematic frame:
# C  0x00000000
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pi/GreengrassCore/hs_err_pid6770.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```

**Comment by MikeDombo** [comment] 2021-03-03 17:09
Empty is not null, so I don't think that should cause a NPE. The cause of the NPE would seem to be that you are calling the method before waiting for the connect future to complete. Does that explanation fit with what you see?

**Comment by fahadmohammed01** [comment] 2021-03-30 17:17
Hi @cthulhuology, This issue hasn’t been active in longer than a week. Because it has been longer than a week since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please provide us with more information on how to replicate this.

**Closed** 2021-04-07 17:18 UTC
Labels: bug, closing-soon
