### ISSUE TITLE
Unquoted characters in JSON formatted error message

### ISSUE THREAD

**Issue by JamesGosling** [aws-greengrass/aws-greengrass-nucleus#847] opened 2021-02-06 20:46 UTC
I’ve been trying to deploy 2.0.4 to a device already running 2.0.3.  It’s failing and I’m still trying to get to the bottom of it.  Along the way I noticed this line in the JSON formatted log:
```{"error": "No serializer found for class com.fasterxml.jackson.core.util.DefaultPrettyPrinter and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.aws.greengrass.logging.impl.GreengrassLogMessage["cause"]->java.io.IOException["cause"]->com.fasterxml.jackson.databind.JsonMappingException["cause"]->com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException["processor"]->com.fasterxml.jackson.dataformat.yaml.YAMLParser["codec"]->com.fasterxml.jackson.databind.ObjectMapper["serializationConfig"]->com.fasterxml.jackson.databind.SerializationConfig["defaultPrettyPrinter"])"}```
It’s a simple key-value pair, where the value is a very long string.  But the string contains ” characters that are not \ quoted — the JSON parser, when parsing this message, says:
```Unexpected character ('c' (code 99)): was expecting comma to separate Object entries```

**Comment by MikeDombo** [comment] 2021-02-06 20:53
The cause of the improper JSON is https://github.com/aws-greengrass/aws-greengrass-logging-java/blob/main/src/main/java/com/aws/greengrass/logging/impl/GreengrassLogMessage.java#L118, however this does not explain why the error is happening to begin with, as we shouldn't be serializing a `DefaultPrettyPrinter`.

**Comment by MikeDombo** [comment] 2021-03-08 18:06
Fixed in logger, will be part of the next release which builds with that logger.

**Closed by MikeDombo** 2021-03-08 18:06 UTC
Labels: bug
