### ISSUE TITLE
Deployment stuck in progress

### ISSUE THREAD

**Issue by tleyden** [aws-greengrass/aws-greengrass-nucleus#807] opened 2021-01-01 18:18 UTC
**Describe the bug**

When I list deployments, one is stuck in progress and is blocking any other deployments:

```
622276f4-ea54-4ae6-a122-4d2a839f34e3: FAILED
acd4723a-1e22-4ef6-ad43-6448ff901dfb: SUCCEEDED
7f44e898-d408-4c1b-94ae-6f86b7b04409: FAILED
d539cffa-14a1-4326-a05d-9d669d0c87f0: IN_PROGRESS
c9d1e4b9-6c80-40f1-8b30-88dd5c419159: SUCCEEDED
20c9f98f-f166-49a1-9969-d9c0fe6aa8b7: FAILED
458e1c61-d303-470a-8e04-03d038586b57: SUCCEEDED
6959ea05-9ec3-4ee2-b28f-7644992e1d1b: SUCCEEDED
9fdf4359-7483-467d-a255-fddd7aace873: FAILED
3bc7dec3-68cf-4f0b-9f09-c583d1f94ab1: QUEUED
```

**To Reproduce**

I was trying to create a docker component based on these instructions: https://docs.aws.amazon.com/greengrass/v2/developerguide/run-docker-container.html

I noticed related permission errors in the component logs, which might have helped cause the issue:

```
2021-01-01T16:00:30.106Z [WARN] (Copier) com.example.MyDockerComponent: stderr. Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/load?quiet=1: dial unix /var/run/docker.sock: connect: permission denied. {scriptName=services.com.example.MyDockerComponent.lifecycle.Install.Script, serviceName=com.example.MyDockerComponent, currentState=NEW}
```

Also in an attempt to fix it, I ran `systemctl restart greengrass` and restarted the device.

**Expected behavior**

The deployment should fail rather than getting stuck in progress.

**Actual behavior**

According to the logs, the deployment failed, but it stayed in the `IN_PROGRESS` state.

```
2021-01-01T16:28:44.484Z [INFO] (Serialized listener processor) com.aws.greengrass.lifecyclemanager.KernelLifecycle: executor-service-shutdown-initiated. {}
2021-01-01T16:28:44.483Z [WARN] (FleetStatusService-lifecycle) com.aws.greengrass.status.FleetStatusService: service-state-transition-interrupted. Service lifecycle thread interrupted. Thread will exit now. {serviceName=FleetStatusService, currentState=FINISHED}
2021-01-01T16:28:44.485Z [INFO] (Thread-1) com.aws.greengrass.lifecyclemanager.KernelLifecycle: Waiting for executors to shutdown. {}
2021-01-01T16:28:44.486Z [ERROR] (pool-2-thread-21) com.aws.greengrass.deployment.activator.DeploymentActivator: merge-config. Deployment failed. {deploymentId=d539cffa-14a1-4326-a05d-9d669d0c87f0}
java.util.concurrent.ExecutionException: java.lang.InterruptedException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.aws.greengrass.deployment.DeploymentConfigMerger$AggregateServicesChangeManager.removeObsoleteServices(DeploymentConfigMerger.java:286)
	at com.aws.greengrass.deployment.activator.DefaultActivator.activate(DefaultActivator.java:85)
	at com.aws.greengrass.deployment.DeploymentConfigMerger.updateActionForDeployment(DeploymentConfigMerger.java:128)
	at com.aws.greengrass.deployment.DeploymentConfigMerger.mergeInNewConfig(DeploymentConfigMerger.java:96)
	at com.aws.greengrass.deployment.DefaultDeploymentTask.call(DefaultDeploymentTask.java:112)
	at com.aws.greengrass.deployment.DefaultDeploymentTask.call(DefaultDeploymentTask.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.aws.greengrass.lifecyclemanager.GreengrassService.lambda$close$2(GreengrassService.java:355)
	... 3 more

2021-01-01T16:28:44.496Z [INFO] (pool-2-thread-21) com.aws.greengrass.deployment.DeploymentService: deployment-task-execution. Finished deployment task. {deploymentId=d539cffa-14a1-4326-a05d-9d669d0c87f0, serviceName=DeploymentService, currentState=FINISHED}
2021-01-01T16:28:44.501Z [INFO] (pool-2-thread-21) com.aws.greengrass.componentmanager.ComponentStore: delete-component-start. {componentIdentifier=com.example.MyDockerComponent-v1.0.0}
2021-01-01T16:28:44.531Z [INFO] (pool-2-thread-21) com.aws.greengrass.componentmanager.ComponentStore: delete-component-finish. {componentIdentifier=com.example.MyDockerComponent-v1.0.0}
```

**Environment**
 - OS: Raspbian Buster
 - JDK version: JDK 1.8
 - Nucleus version: v2.0.3 (this is the latest release, and I installed it yesterday -- not sure how to confirm this)

**Comment by shaguptashaikh** [comment] 2021-01-04 19:53
Hi tleyden,

Thanks for using Greengrass and reporting the issue. In order to reproduce and understand the root cause for this, we will need more information. Can you answer the following (excluding any confidential information)?
- Are you able to share more logs for the nucleus (<root>/logs/greengrass.log or <root>/logs/greengrass<-date-count-suffix).log)? From the logs you've shared above it looks like the deployment processing did finish but it didn't change the status but the logs for that part aren't in there right now.
- Are you able to share logs for the `MyDockerComponent ` component that you were trying to deploy? This will give an idea about how the lifecycle/states were changing. 
- How did you trigger the deployment? Using the local greengrass cli or from the cloud? 
- What was the configuration for the deployment? i.e. did it include any public components, what were the deployment policies, did the deployment that was stuck in `IN_PROGRESS` stage cause nucleus restart?

**Comment by tleyden** [comment] 2021-01-06 01:01
Hi @shaguptashaikh, yes I still have the logs and can share them.  Is it safe to share via github or is there an email address I can send to>

> How did you trigger the deployment? Using the local Greengrass CLI or from the cloud?

From the CLI

> What was the configuration for the deployment? i.e. did it include any public components, what were the deployment policies

There were no public components or any deployment policies I know of.  I was trying to follow the example steps in https://docs.aws.amazon.com/greengrass/v2/developerguide/run-docker-container.html.

> did the deployment that was stuck in IN_PROGRESS stage cause nucleus restart?

No it didn't cause a nucleas restart that I noticed.

I was able to workaround the issue by deleting the `/greengrass/v2` and re-installing.

**Comment by fahadmohammed01** [comment] 2021-01-06 19:34
Hi @tleyden, You can share the logs via GitHub if you are comfortable (logs shared via GitHub issues will be available to public). If you prefer to share the logs privately, we will get back with an alternative.

**Comment by fahadmohammed01** [comment] 2021-01-15 18:47
Hi @tleyden, You can share the logs privately by sending a private message to faham via [aws forum](https://forums.aws.amazon.com).

**Comment by tleyden** [comment] 2021-01-15 19:02
Thanks, will do!

**Comment by fahadmohammed01** [comment] 2021-01-28 17:40
Hi @tleyden, This issue hasn’t been active in longer than a week. Because it has been longer than a week since the last update on this, and in the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please send us the requested information.

**Closed** 2021-02-01 18:12 UTC
Labels: bug, closing-soon
