### ISSUE TITLE
( com.aws.greengrass.tes.CredentialRequestHandler): Encountered error while fetching credentials

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1021] opened 2021-07-09 16:55 UTC
**Describe the bug**
After I create a deployment, the error message as shown below will showed up repeatedly in the `/greengrass/v2/logs/greengrass.log`. 
```
2021-07-09T13:28:24.097Z [WARN] (pool-2-thread-20) com.aws.greengrass.tes.CredentialRequestHandler: Encountered error while fetching credentials. {iotCredentialsPath=/role-aliases/GreengrassV2Tok[63/1812]
eRoleAlias/credentials}                                                                                                                                                                                     
com.aws.greengrass.deployment.exceptions.AWSIotException: Unable to get response                                                                                                                                    at com.aws.greengrass.iot.IotCloudHelper.getHttpResponse(IotCloudHelper.java:87)
        at com.aws.greengrass.iot.IotCloudHelper.lambda$sendHttpRequest$1(IotCloudHelper.java:72)                                                                                                                   at com.aws.greengrass.util.BaseRetryableAccessor.retry(BaseRetryableAccessor.java:32)                                                                                                               
        at com.aws.greengrass.iot.IotCloudHelper.sendHttpRequest(IotCloudHelper.java:73)                                                                                                                    
        at com.aws.greengrass.tes.CredentialRequestHandler.getCredentialsBypassCache(CredentialRequestHandler.java:168)                                                                                             at com.aws.greengrass.tes.CredentialRequestHandler.getCredentials(CredentialRequestHandler.java:254)
        at com.aws.greengrass.tes.CredentialRequestHandler.getAwsCredentials(CredentialRequestHandler.java:263)                                                                                                     at com.aws.greengrass.tes.TokenExchangeService.resolveCredentials(TokenExchangeService.java:136)
        at com.aws.greengrass.tes.LazyCredentialProvider.resolveCredentials(LazyCredentialProvider.java:33)                                          
        at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:76)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:97)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
        at software.amazon.awssdk.services.cloudwatchlogs.DefaultCloudWatchLogsClient.putLogEvents(DefaultCloudWatchLogsClient.java:2873)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.uploadLogs(CloudWatchLogsUploader.java:128)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.lambda$upload$0(CloudWatchLogsUploader.java:60)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.upload(CloudWatchLogsUploader.java:59) 
        at com.aws.greengrass.logmanager.LogManagerService.processLogsAndUpload(LogManagerService.java:567)
        at com.aws.greengrass.logmanager.LogManagerService.startup(LogManagerService.java:579)
        at com.aws.greengrass.lifecyclemanager.Lifecycle.lambda$handleStateTransitionStartingToRunningAsync$9(Lifecycle.java:531)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: cylrbfvuhpzxn.credentials.iot.us-west-2.amazonaws.com
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)
        at com.sun.proxy.$Proxy16.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:253)
        at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:106)
        at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:232)
at com.aws.greengrass.iot.IotCloudHelper.getHttpResponse(IotCloudHelper.java:80)
        ... 28 more

2021-07-09T13:28:24.098Z [ERROR] (pool-2-thread-20) com.aws.greengrass.tes.CredentialRequestHandler: Error in retrieving AwsCredentials from TES. {iotCredentialsPath=/role-aliases/GreengrassV2TokenExchang
eRoleAlias/credentials, credentialData=Failed to get connection}
2021-07-09T13:28:24.098Z [ERROR] (pool-2-thread-20) com.aws.greengrass.logmanager.CloudWatchLogsUploader: Unable to upload logs for log group /aws/greengrass/UserComponent/us-west-2/burro-dev-deployer. {}
software.amazon.awssdk.core.exception.SdkClientException: Failed to fetch credentials
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
        at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:39) 
        at com.aws.greengrass.tes.LazyCredentialProvider.resolveCredentials(LazyCredentialProvider.java:40)
        at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:76)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:97)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
        at software.amazon.awssdk.services.cloudwatchlogs.DefaultCloudWatchLogsClient.putLogEvents(DefaultCloudWatchLogsClient.java:2873)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.uploadLogs(CloudWatchLogsUploader.java:128)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.lambda$upload$0(CloudWatchLogsUploader.java:60)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at com.aws.greengrass.logmanager.CloudWatchLogsUploader.upload(CloudWatchLogsUploader.java:59) 
        at com.aws.greengrass.logmanager.LogManagerService.processLogsAndUpload(LogManagerService.java:567)
        at com.aws.greengrass.logmanager.LogManagerService.startup(LogManagerService.java:579)
        at com.aws.greengrass.lifecyclemanager.Lifecycle.lambda$handleStateTransitionStartingToRunningAsync$9(Lifecycle.java:531)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2021-07-09T13:28:25.247Z [INFO] (pool-2-thread-20) com.aws.greengrass.tes.CredentialRequestHandler: Received IAM credentials that will be cached until 2021-07-09T14:23:25Z. {iotCredentialsPath=/role-alias
es/GreengrassV2TokenExchangeRoleAlias/credentials}
2021-07-09T13:28:51.004Z [INFO] (pool-2-thread-14) com.aws.greengrass.deployment.IotJobsHelper: Timed out while updating the job status. {ThingName=burro-7-058}
2021-07-09T13:28:51.005Z [INFO] (pool-2-thread-14) com.aws.greengrass.deployment.DeploymentDirectoryManager: Persist link to last deployment. {link=/greengrass/v2/deployments/previous-failure}
2021-07-09T13:28:51.005Z [INFO] (pool-2-thread-14) com.aws.greengrass.deployment.DeploymentDirectoryManager: Clean up link to earlier deployment. {link=/greengrass/v2/deployments/previous-failure}
2021-07-09T13:29:18.800Z [INFO] (pool-2-thread-9) com.aws.greengrass.deployment.ShadowDeploymentListener: Subscribed to update named shadow accepted topic. {}
2021-07-09T13:29:18.897Z [INFO] (pool-2-thread-9) com.aws.greengrass.deployment.ShadowDeploymentListener: Subscribed to update named shadow rejected topic. {}
2021-07-09T13:29:18.998Z [INFO] (pool-2-thread-9) com.aws.greengrass.deployment.ShadowDeploymentListener: Subscribed to get named shadow topic. {}
2021-07-09T13:29:19Z [INFO] (pool-2-thread-9) com.aws.greengrass.deployment.ShadowDeploymentListener: Published to get named shadow topic. {}
2021-07-09T13:29:19.122Z [INFO] (Thread-6) com.aws.greengrass.deployment.ShadowDeploymentListener: Last known deployment status is empty, nothing to report. {}
2021-07-09T13:29:19.135Z [INFO] (Thread-6) com.aws.greengrass.deployment.ShadowDeploymentListener: Deployment result already reported. Ignoring shadow update at startup. {CONFIGURATION_ARN=arn:aws:greengr
ass:us-west-2:011715402690:configuration:thing/burro-7-058:1}
2021-07-09T13:29:20.262Z [INFO] (pool-2-thread-8) com.aws.greengrass.deployment.IotJobsHelper: Subscribed to deployment job execution update.. {ThingName=burro-7-058}
2021-07-09T13:29:20.355Z [INFO] (pool-2-thread-8) com.aws.greengrass.deployment.IotJobsHelper: Subscribed to deployment job event notifications.. {ThingName=burro-7-058}
2021-07-09T13:29:20.356Z [INFO] (pool-2-thread-8) com.aws.greengrass.deployment.IotJobsHelper: Connection established to IoT cloud. {ThingName=burro-7-058}
```

**To Reproduce**
1. Create a role and download a pair of AWS credential `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY`. And set them as environment variable.
2. Download the greengrass core and unzip it by   
```
curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > greengrass-nucleus-latest.zip
unzip greengrass-nucleus-latest.zip -d GreengrassCore && rm greengrass-nucleus-latest.zip
```
3. Install the greengrass core as a system service by  
```
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE -jar ./GreengrassCore/lib/Greengrass.jar --aws-region us-west-2 --thing-name $HOSTNAME  --component-default-user $USER:docker --provision true --setup-system-service true --deploy-dev-tools true
```
4. Create a component to deploy on the target device from another computer.
5. Type `sudo cat /greengrass/v2/logs/greengrass.log` to see the log.

**Expected behavior**
I expect the credential could be fetched successfully.

**Actual behavior**
It kept retrying to fetch and some components require the credential would got stuck.

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: Java 8
 - Nucleus version: 2.2.0

**Additional context**
This is the first time I see these error log about credential.  I deployed to remote targets several times in the past 3 days but none got these error messages. Is it the case that one core device received two deployments at the same time? One from the thing group and the other one from the thing.  
In the end all deployments on many target devices replied `failed`. So the logs are polluted and I cannot tell if the deployment really finished or not.

**Comment by MikeDombo** [comment] 2021-07-09 16:57
This is the same DNS issue which is showing up in #1020. Closing as duplicate.

**Comment by MikeDombo** [comment] 2021-07-09 16:58
`Caused by: java.net.UnknownHostException: cylrbfvuhpzxn.credentials.iot.us-west-2.amazonaws.com`

**Closed by MikeDombo** 2021-07-09 16:57 UTC
Labels: bug, needs-triage
