### ISSUE TITLE
(greengrass loder): export PATH for JAVA_HOME

### ISSUE THREAD

**Issue by youngah** [aws-greengrass/aws-greengrass-nucleus#1271] opened 2022-07-25 23:55 UTC
**Describe the bug**
i am just starting for new project of greengrass iot
but my device has a very small memory then i want to install corretto to another partition.
when boot time. i mount corretto install folder to " /opt-aws/". the java path is changed.
i got a problem when i try to launch greengrass service....
then i got a error.  can't found java command

**To Reproduce**

**Expected behavior**
get java path and launch with no error

**Actual behavior**
journalctl log
/opt-aws/greengrass/v2/alts/current/distro/bin/loader: line 40: java: command not found
I found loader file has call "java" point.
how about add "export PATH =$PATH:JAVA_HOME" into loader file.

**Environment**
 - OS: [e.g. Ubuntu 18.04]
 - JDK version: Corretto-11.0.12.7.1
 - Nucleus version:2.5.6

**Additional context**

E.g. what is the impact of the bug?

**Comment by MikeDombo** [comment] 2022-07-26 00:03
You can symlink java so that it will be included in the search of PATH.

You may also edit the systemd service definition (`/etc/systemd/system/greengrass.service`) to set your own path, such as:

```
[Service]
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:<path to corretto>"
```

This is not a bug with Greengrass, but with how you have installed Java. Please correct the Java installation or use the provided work around.

**Closed by MikeDombo** 2022-07-26 00:03 UTC
Labels: bug, needs-triage
