### ISSUE TITLE
(aws-greengrass-nucleus): Run on read-only root filesystem

### ISSUE THREAD

**Issue by kennu** [aws-greengrass/aws-greengrass-nucleus#986] opened 2021-05-26 19:38 UTC
**Feature Description**
Run on read-only root filesystem

**Use Case**
We deploy and update our IoT devices with Yocto Linux and Mender. The Linux image is burned to a partition and mounted as read-only root filesystem. On the next update, we replace the entire partition with a new image. Persistent data is kept on a separate writable data partition (mounted in /data).

**Proposed Solution**
Greengrass V1 supports this with the [writeDirectory](https://docs.aws.amazon.com/greengrass/v1/developerguide/gg-core.html) setting. It allows us to update the Greengrass software on the read-only root partition, and Greengrass writes its own data files into a separate data partition. We would like to have a **writeDirectory** configuration directive also in Greengrass V2.

Please note that this also requires that Greengrass doesn't attempt to modify the root filesystem in other ways, such as executing shell commands that make changes outside /tmp and /data.

**Comment by MikeDombo** [comment] 2021-05-26 19:39
Closing as duplicate of #830

**Comment by MikeDombo** [comment] 2021-05-26 19:40
In your use case you don't want to use Greengrass to handle deployments? Why not, and what do you use Greengrass for?

**Closed by MikeDombo** 2021-05-26 19:39 UTC
Labels: needs-triage
